#![allow(clippy::expect_used)]

use arbitrary::Unstructured;
use iamf::fuzzing::sequence_from_fuzz_bytes;
use iamf::sequence::{SequenceObu, parse_sequence, write_parsed_sequence};

#[test]
fn bounded_generator_models_survive_structural_and_byte_round_trips() {
    let mut saw_empty = false;
    let mut saw_descriptors_only = false;
    let mut saw_unknown = false;
    let mut saw_redundant = false;

    for shape in 0_u8..=31 {
        let mut input = vec![shape];
        input.extend((0_u8..=255).cycle().take(512));
        let mut unstructured = Unstructured::new(&input);
        let sequence = sequence_from_fuzz_bytes(&mut unstructured)
            .expect("the fixed smoke input is large enough");

        saw_empty |= sequence.obus.is_empty();
        saw_descriptors_only |= !sequence.obus.is_empty()
            && !sequence.obus.iter().any(|obu| {
                matches!(
                    obu,
                    SequenceObu::ParameterBlock(_)
                        | SequenceObu::TemporalDelimiter(_)
                        | SequenceObu::AudioFrame(_)
                )
            });
        saw_unknown |= sequence
            .obus
            .iter()
            .any(|obu| matches!(obu, SequenceObu::Unknown(_)));
        saw_redundant |= sequence.obus.iter().any(|obu| {
            matches!(obu, SequenceObu::AudioElement(element) if element.header.obu_redundant_copy)
        });

        assert!(sequence.obus.len() <= 40, "model stays deliberately small");
        let bytes = write_parsed_sequence(Vec::new(), &sequence).expect("generated model writes");
        let parsed = parse_sequence(&bytes).expect("generated bytes parse");
        assert_eq!(parsed, sequence);
        assert_eq!(
            write_parsed_sequence(Vec::new(), &parsed).expect("parsed model rewrites"),
            bytes
        );
    }

    assert!(saw_empty);
    assert!(saw_descriptors_only);
    assert!(saw_unknown);
    assert!(saw_redundant);
}
