//! Committed expectation inventory for the foreign reference corpus.
//!
//! Values in this module are transcribed from paired upstream textprotos or
//! `PHASE2-EXPECTATION-PROVENANCE.md`; they are never generated by the parser
//! under test.

#[derive(Debug, Clone, Copy)]
pub struct PositiveExpectation {
    pub path: &'static str,
}

#[derive(Debug, Clone, Copy)]
pub struct NegativeExpectation {
    pub path: &'static str,
    pub zero_frame_size: u32,
    pub finding_field: &'static str,
    pub finding_message: &'static str,
}

pub const POSITIVE_EXPECTATIONS: &[PositiveExpectation] = &[
    PositiveExpectation { path: "test_000000_3.iamf" },
    PositiveExpectation { path: "test_000002.iamf" },
    PositiveExpectation { path: "test_000003.iamf" },
    PositiveExpectation { path: "test_000005.iamf" },
    PositiveExpectation { path: "test_000006.iamf" },
    PositiveExpectation { path: "test_000007.iamf" },
    PositiveExpectation { path: "test_000012.iamf" },
    PositiveExpectation { path: "test_000013.iamf" },
    PositiveExpectation { path: "test_000015.iamf" },
    PositiveExpectation { path: "test_000016.iamf" },
    PositiveExpectation { path: "test_000017.iamf" },
    PositiveExpectation { path: "test_000018.iamf" },
    PositiveExpectation { path: "test_000019.iamf" },
    PositiveExpectation { path: "test_000059.iamf" },
    PositiveExpectation { path: "test_000060.iamf" },
    PositiveExpectation { path: "test_000062.iamf" },
    PositiveExpectation { path: "test_000063.iamf" },
    PositiveExpectation { path: "test_000067.iamf" },
    PositiveExpectation { path: "test_000071.iamf" },
    PositiveExpectation { path: "test_000077.iamf" },
    PositiveExpectation { path: "test_000078.iamf" },
    PositiveExpectation { path: "test_000079.iamf" },
    PositiveExpectation { path: "test_000085.iamf" },
    PositiveExpectation { path: "test_000088.iamf" },
    PositiveExpectation { path: "test_000097.iamf" },
    PositiveExpectation { path: "test_000119.iamf" },
    PositiveExpectation { path: "test_000120.iamf" },
    PositiveExpectation { path: "test_000121.iamf" },
    PositiveExpectation { path: "test_000122.iamf" },
    PositiveExpectation { path: "test_000124.iamf" },
    PositiveExpectation { path: "test_000129.iamf" },
    PositiveExpectation { path: "test_000130.iamf" },
    PositiveExpectation { path: "test_000501.iamf" },
    PositiveExpectation { path: "test_000503.iamf" },
    PositiveExpectation {
        path: "iamf-tools/noise_1024samp_5p1_opus.iamf",
    },
    PositiveExpectation {
        path: "iamf-tools/noise_1024samp_stereo_flac.iamf",
    },
    PositiveExpectation {
        path: "iamf-tools/noise_3s_stereo_opus.iamf",
    },
    PositiveExpectation {
        path: "iamf-tools/tones_100ms_3OA_stereo_opus.iamf",
    },
];

pub const NEGATIVE_EXPECTATION: NegativeExpectation = NegativeExpectation {
    path: "negative/tones_256samp_5p1_pcm.iamf",
    zero_frame_size: 0,
    finding_field: "num_samples_per_frame",
    finding_message: "num_samples_per_frame is 0, outside 1..=96000",
};
