#!/usr/bin/env bash
#
# check-float-escape-census.sh — D-21 / PROF-03 / GUARD-11
#
# The crate bans f32/f64 (clippy.toml `disallowed-types`). PROF-03 needs exactly
# one float conversion, `src/model/loudness.rs` `lufs_to_q7_8`, and D-21
# sanctions exactly one lint escape for it. This script is the census that
# holds that line: it lists every attribute in src/ that could silence
# `clippy::disallowed_types` and exits 0 only when there is exactly one, in
# src/model/loudness.rs.
#
# Why this script exists (quick task 260914-38r): the census used to be a
# single-line text search for an `allow` followed by `disallowed_types` on the
# same line. rustfmt formats the sanctioned attribute over several lines —
# `#[allow(` alone on one line, `clippy::disallowed_types,` on the next — so
# that search returned zero hits on the committed tree. It could not see the
# sanctioned escape, and it could not have seen a second one written the same
# way. A guardrail that is documented but cannot fire is worse than none.
#
# Coverage. The scan is multi-line and matches:
#   - `allow(...)` and `expect(...)`;
#   - outer `#[...]`, inner `#![...]` and inside `cfg_attr(..., ...)` (the
#     pattern is deliberately not anchored to `#[`);
#   - the lint named with or without the `clippy::` prefix, anywhere in the
#     lint list;
#   - the lint groups `clippy::all` and `clippy::style`, which contain
#     `disallowed_types`. A clippy 1.85 experiment (crate with
#     `disallowed_types = "deny"` and f64 banned) showed `#[allow(clippy::style)]`,
#     `#[allow(clippy::all)]` and `#[cfg_attr(not(test),
#     expect(clippy::disallowed_types))]` each silence the lint, so they are
#     real escapes.
# Lines whose first non-blank characters are `//` (plain, doc and inner doc
# comments) are blanked before matching, keeping their newlines so reported
# line numbers stay right. The census is textual: it scans every `.rs` file
# under src/, whether or not it is registered as a module.
#
# Known limits, documented rather than fixed:
#   - `/* */` block comments and trailing `//` comments after code are not
#     stripped. A false positive fails loudly (exit 1 naming file:line), never
#     silently.
#   - An attribute generated by a macro is invisible to a textual scan.
#
# Why perl, not rg: tools/prove-guards.sh runs this on the ubuntu CI runner,
# where ripgrep is not guaranteed. perl is Essential on Debian/Ubuntu
# (perl-base) and ships with macOS.
#
# Why exactly one, not at most one: the tree has exactly one, and zero means
# PROF-03's escape was lost (or the census stopped seeing it).
#
# Usage: check-float-escape-census.sh [--root PATH]
#   PATH is a non-symlink directory containing src/ (default: the repo root).
# Output: one `src/<path>.rs:<line>` per hit, then a summary line.
# Exit: 0 exactly one hit, in src/model/loudness.rs
#       1 any other count or location
#       2 usage or environment error (bad root, no src/, no perl, scan failed)

set -euo pipefail

SCRIPT_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
    printf 'usage: %s [--root PATH]\n' "${0##*/}" >&2
    exit 2
}

canonical_root() {
    local candidate="$1"
    if [[ ! -d "${candidate}" || -L "${candidate}" ]]; then
        printf 'root must be a non-symlink directory: %s\n' "${candidate}" >&2
        exit 2
    fi
    (cd -P "${candidate}" && pwd)
}

ROOT="${SCRIPT_ROOT}"
case "${1:-}" in
    '')
        [[ $# -eq 0 ]] || usage
        ;;
    --root)
        [[ $# -eq 2 ]] || usage
        ROOT="$(canonical_root "$2")"
        ;;
    *) usage ;;
esac

if [[ ! -d "${ROOT}/src" ]]; then
    printf 'no src/ directory under %s\n' "${ROOT}" >&2
    exit 2
fi
if ! command -v perl >/dev/null 2>&1; then
    printf 'perl is required for the float escape census\n' >&2
    exit 2
fi

# shellcheck disable=SC2016 # the perl program is single-quoted on purpose
PERL_PROGRAM='
    s{^([ \t]*)//[^\n]*}{$1}mg;
    while (/\b(?:allow|expect)\s*\(\s*(?:[\w:]+\s*,\s*)*(?:(?:clippy::)?disallowed_types|clippy::(?:all|style))\b/g) {
        my $line = 1 + (substr($_, 0, $-[0]) =~ tr/\n//);
        print "$ARGV:$line\n";
    }
'

if ! HITS="$(cd "${ROOT}" \
        && find src -type f -name '*.rs' -print0 \
        | LC_ALL=C sort -z \
        | xargs -0 -r perl -0777 -ne "${PERL_PROGRAM}")"; then
    printf 'float escape census: the scan itself failed under %s\n' "${ROOT}" >&2
    exit 2
fi

COUNT=0
if [[ -n "${HITS}" ]]; then
    printf '%s\n' "${HITS}"
    COUNT="$(printf '%s\n' "${HITS}" | wc -l | tr -d ' ')"
fi
printf 'float escape census: %s hit(s); exactly 1 expected, in src/model/loudness.rs\n' "${COUNT}"

if [[ "${COUNT}" -eq 1 && "${HITS}" == src/model/loudness.rs:* ]]; then
    exit 0
fi

if [[ "${COUNT}" -eq 0 ]]; then
    printf 'PROF-03 escape lost: no disallowed_types escape found in src/ (expected one in src/model/loudness.rs)\n' >&2
elif [[ "${COUNT}" -eq 1 ]]; then
    printf 'escape moved: the single disallowed_types escape is not in src/model/loudness.rs\n' >&2
else
    printf 'scope breach: %s disallowed_types escapes in src/; D-21 allows exactly one — investigate, do not silence\n' "${COUNT}" >&2
fi
exit 1
